import { BookOpen, MessageSquare, PenLine, Play, Plus, Sparkles } from 'lucide-react'
import { useState } from 'react'
import { MockFormDialog } from '../components/MockFormDialog'
import { PageHeader } from '../components/PageHeader'
import { useApp, useIllustration } from '../features/app/AppStore'

export function MaterialsPage() {
  const { state, actions } = useApp(); const [selectedId, setSelectedId] = useState(state.materials[2].id); const [tab, setTab] = useState('全部'); const [creating, setCreating] = useState(false); const [title, setTitle] = useState(''); const [type, setType] = useState('专题研究'); const mountains = useIllustration('mountains')
  const tabs = ['全部','参考作品','专题研究','已学会','处理中','需要处理']; const selected = state.materials.find((material) => material.id === selectedId) ?? state.materials[0]
  const submit = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const id = actions.createMaterial({ title: title.trim(), type }); setSelectedId(id); setTab('全部'); setCreating(false); setTitle('') }
  return <div className="page"><PageHeader title="素材与学习" subtitle="在这里添加、整理并研究素材，让 AI 从你的资料中学习，写出更好的作品。" art={mountains}/>
    <div className="filterbar panel">{tabs.map((item) => <button key={item} className={tab === item ? 'active' : ''} onClick={() => setTab(item)}>{item}</button>)}<button className="primary" onClick={() => setCreating(true)}><Plus/>添加素材 / 发起研究</button></div>
    <div className="split materials-layout"><section className="panel material-list"><h3>全部素材与研究 <small>（{state.materials.length}）</small></h3>{state.materials.filter((material) => tab === '全部' || material.type === tab || material.status === tab).map((material) => <button key={material.id} className={selected.id === material.id ? 'selected' : ''} onClick={() => setSelectedId(material.id)}><span className="material-thumb">{material.type === '专题研究' ? '研' : '书'}</span><span><strong>{material.title}</strong><small>{material.type}　·　{material.date}</small></span><em>{material.status}</em></button>)}</section>
    <section className="panel material-detail"><div className="detail-title"><span className="material-thumb large">{selected.type === '专题研究' ? '研' : '书'}</span><div><h2>{selected.title} <button className="icon-button" aria-label="编辑素材标题" onClick={() => actions.openDialog('编辑素材', `正在编辑「${selected.title}」的 Mock 条目。`)}><PenLine size={17}/></button></h2><p>{selected.type}　更新于 {selected.date}</p></div><span className="soft-tag">{selected.status}</span></div><div className="learning"><h3><Sparkles/>AI 从这里学到了什么</h3><p>{selected.summary}</p><ul>{selected.knowledge.map((item) => <li key={item}>{item}</li>)}</ul><div><button onClick={() => actions.openDialog('研究稿', `${selected.title}：${selected.summary}`)}><BookOpen/>查看研究稿</button><button onClick={() => actions.notify(`已继续「${selected.title}」的 Mock 学习任务`)}><Play/>继续学习</button><button onClick={() => actions.openDialog('问 AI', `围绕「${selected.title}」提问的 Mock 对话已准备好。`)}><MessageSquare/>问 AI</button></div></div><h3><Sparkles/>已学会的知识</h3><div className="knowledge-grid">{selected.knowledge.map((item, index) => <article key={item}><strong>{item}</strong><p>{['可复用的视觉与叙事特征。','帮助组织城市空间和人物处境。','用于控制主题、情绪与节奏。'][index] ?? '等待继续整理。'}</p></article>)}</div></section></div>
    {creating && <MockFormDialog title="添加素材 / 发起研究" submitLabel="创建" onClose={() => setCreating(false)} onSubmit={submit}><label>名称<input autoFocus value={title} onChange={(event) => setTitle(event.target.value)} placeholder="素材名称或研究主题" required/></label><label>类型<select value={type} onChange={(event) => setType(event.target.value)}><option>专题研究</option><option>参考作品</option><option>参考素材</option></select></label></MockFormDialog>}
  </div>
}
