import { Bot, Box, Check, ChevronDown, Cloud, Folder, Image, Plus, RotateCcw, Settings as SettingsIcon, SlidersHorizontal, Wifi } from 'lucide-react'
import { useRef, useState } from 'react'
import { PageHeader } from '../components/PageHeader'
import { illustrationLabels } from '../assets/illustrations'
import { useApp, useIllustration } from '../features/app/AppStore'
import type { IllustrationKey } from '../contracts/ui'

const menu = [{label:'AI 服务 / API',Icon:Cloud},{label:'Agent',Icon:Bot},{label:'执行配置',Icon:SlidersHorizontal},{label:'项目与数据',Icon:Folder},{label:'插图与视觉',Icon:Image},{label:'高级设置',Icon:SettingsIcon}]
export function SettingsPage() {
  const { state, actions } = useApp(); const [section,setSection]=useState('AI 服务 / API'); const [testing,setTesting]=useState<string|null>(null); const input=useRef<HTMLInputElement>(null); const [target,setTarget]=useState<IllustrationKey>('city')
  const city=useIllustration('city'); const services=[['DeepSeek','https://api.deepseek.com','deepseek-chat'],['OpenAI 兼容服务','https://api.openai-proxy.com/v1','gpt-5'],['本地服务 Ollama','http://127.0.0.1:11434','llama3']]
  const upload=(file?:File)=>{if(!file)return;actions.setIllustration(target,URL.createObjectURL(file))}
  return <div className="page"><PageHeader title="设置" subtitle="管理应用配置、AI 服务与个性化偏好" art={city}/><div className="settings-layout"><aside className="panel settings-menu">{menu.map(({label,Icon})=><button key={label} className={section===label?'active':''} onClick={()=>setSection(label)}><Icon/>{label}</button>)}<div style={{backgroundImage:`url(${useIllustration('desk')})`}}/></aside>
  <section className="panel settings-content">{section==='AI 服务 / API'?<><div className="section-title"><div><h2>AI 服务 / API</h2><p>配置并管理 AI 服务连接，支持多服务并存，可在创作时自由切换。</p></div><button className="primary"><Plus/>添加服务</button></div>{services.map(([name,url,model],i)=><article className="service" key={name}><header><span className={`provider p${i}`}><Box/></span><h3>{name}</h3>{i===0&&<span className="soft-tag">默认</span>}<em><Check/>已连接</em><ChevronDown/></header><div className="service-row"><span>API 地址<strong>{url}</strong></span><span>API Key<strong>{i===2?'不需要':'sk-****************89ab'}</strong></span><button onClick={async()=>{setTesting(name);await new Promise(r=>setTimeout(r,700));setTesting(null)}}><Wifi/>{testing===name?'测试中…':'测试连接'}</button><button><Box/>管理模型</button></div><footer>可用模型　<span>{model} ✓</span>　<span>{i===0?'deepseek-reasoner':'更多模型'}</span></footer></article>)}</>:<><div className="section-title"><div><h2>{section}</h2><p>本阶段所有配置仅保存在前端 Mock state。</p></div></div>{section==='插图与视觉'?<div className="illustration-settings"><div className="illustration-tabs">{(Object.keys(illustrationLabels) as IllustrationKey[]).map(k=><button key={k} className={target===k?'active':''} onClick={()=>setTarget(k)}>{illustrationLabels[k]}</button>)}</div><div className="illustration-preview" style={{backgroundImage:`url(${state.illustrations.custom[target]??state.illustrations.defaults[target]})`}}/><input ref={input} hidden type="file" accept="image/*" onChange={(e)=>upload(e.target.files?.[0])}/><div><button className="primary" onClick={()=>input.current?.click()}><Image/>更换自定义图片</button><button onClick={()=>actions.resetIllustration(target)}><RotateCcw/>恢复默认</button></div></div>:<div className="mock-config"><SlidersHorizontal size={42}/><h3>{section} Mock 配置</h3><p>这里展示可操作的界面占位，不会调用或修改真实后台。</p><label><input type="checkbox" defaultChecked/> 启用自动保存提示</label><label><input type="checkbox"/> 在执行完成时播放提示音</label></div>}</>}</section></div></div>
}
