import { Bot, Check, ChevronDown, CircleCheck, MoreHorizontal, PenLine, Plus, RefreshCw, Sparkles, Type } from 'lucide-react'
import { useApp } from '../features/app/AppStore'
import { StatusBadge } from '../components/StatusBadge'

export function WritingPage() {
  const { state, actions }=useApp(); const chapter=state.chapters.find(c=>c.id===state.activeChapterId)??state.chapters[0]
  return <div className="writing-layout"><aside className="panel chapters"><header><h2>章节目录</h2><button><Plus/></button></header>{state.chapters.map(c=><button key={c.id} className={chapter.id===c.id?'active':''} onClick={()=>actions.setChapter(c.id)}>{c.done&&<CircleCheck/>}<span>{c.title}<small>{c.words?`${c.words.toLocaleString()} 字`:'未开始'}</small></span></button>)}<button className="new-chapter"><Plus/>新章节</button></aside>
    <section className="panel editor"><header><h2>{chapter.title}</h2><span>{chapter.words.toLocaleString()} 字 <ChevronDown/>　<Type/>　<MoreHorizontal/></span></header><textarea aria-label="正文编辑区" value={chapter.content} onChange={(e)=>actions.updateChapter(e.target.value)} placeholder="从这里开始写作…"/><footer><span>{chapter.words.toLocaleString()} 字　　预计阅读 9 分钟</span><span><CircleCheck/>自动保存中…</span><span>上次保存：14:32:05</span></footer></section>
    <aside className="writing-side"><section className="panel assistant"><header><h2><Sparkles/>AI 助手</h2></header><h3>现在建议</h3><div className="suggestion">💡 本章营造了怀旧与悬疑并存的氛围，可以深入探索仓库中发现的旧物或线索。</div><button onClick={()=>actions.setProsePrompt('继续探索仓库里的旧物线索')}><PenLine/>接下来怎么写</button><button onClick={()=>actions.setProsePrompt('给我几个不同的情节方案')}><Bot/>给我几个方案</button><button>▣ 帮我看看问题</button></section>
    <section className="panel prose-candidate"><header><h2><Sparkles/>AI 候选稿</h2>{state.writingStatus!=='idle'&&<StatusBadge status={state.writingStatus}/>}</header>{state.writingStatus==='running'?<div className="running"><span/>AI 正在续写候选正文…</div>:<><textarea value={state.proseCandidate} onChange={(e)=>actions.editProse(e.target.value)} placeholder="输入你希望 AI 接下来写什么，然后生成候选稿。"/><input value={state.prosePrompt} onChange={(e)=>actions.setProsePrompt(e.target.value)} placeholder="这一段想写什么？"/><div>{state.writingStatus==='waiting_confirmation'?<><button className="primary" onClick={actions.acceptProse}><Check/>采用</button><button onClick={actions.generateProse}><RefreshCw/>换一种</button><button onClick={actions.discardProse}>不用了</button></>:state.writingStatus==='accepted'?<><span className="accepted-note"><Check/>候选正文已采用并更新编辑区</span><button onClick={actions.discardProse}>继续协作</button></>:<button className="primary wide" onClick={actions.generateProse}><Sparkles/>生成候选正文</button>}</div></>}</section></aside>
  </div>
}
